application: byui-resources
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.html)
  static_files: \1
  upload: .*\.html


- url: /app
  static_dir: app

- url: /assets
  static_dir: assets
  http_headers:
    Access-Control-Allow-Origin: "*"